var PADDING_BETWEEN_TILES = 15;

module.exports = {

  PADDING_BETWEEN_TILES: PADDING_BETWEEN_TILES,

  MIN_COLUMN_COUNT: 0,

  MAX_COLUMN_COUNT: 2,

  TARGET_COLUMN_WIDTH: (1280 - (PADDING_BETWEEN_TILES * 2)) / 2,

  ONE_SIXTIETH: 100 / 6,

  LAYOUT_ANIMATION_TIMEOUT: 800,

  LAYOUT_ANIMATION_DURATION: 250,

  MIN_WIDTH_WHERE_NAME_VISIBLE: 375,

  TILE_DIMENSIONS_RATIO: (1 / 1.61803398874989484820) / 2,

  BIG_TILE_HEIGHT_RATIO: 4, // Height of 4 small tiles

  BIG_TILE_WIDTH_RATIO: 2 // Width of 2 small tiles

};