require 'jar_dependencies'
JBUNDLER_LOCAL_REPO = Jars.home
JBUNDLER_JRUBY_CLASSPATH = []
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/headius/invokebinder/1.2/invokebinder-1.2.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/joda-time/joda-time/2.3/joda-time-2.3.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/github/jnr/jnr-posix/3.0.1/jnr-posix-3.0.1.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/headius/options/1.1/options-1.1.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/ow2/asm/asm-analysis/4.0/asm-analysis-4.0.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/ow2/asm/asm-util/4.0/asm-util-4.0.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/ow2/asm/asm-commons/4.0/asm-commons-4.0.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/jruby/jruby-stdlib/1.7.13/jruby-stdlib-1.7.13.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/jruby/joni/joni/2.1.1/joni-2.1.1.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/jruby/jruby-core/1.7.13/jruby-core-1.7.13.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/github/jnr/jffi/1.2.7/jffi-1.2.7.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/github/jnr/jnr-constants/0.8.5/jnr-constants-0.8.5.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/ow2/asm/asm-tree/4.0/asm-tree-4.0.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/jcraft/jzlib/1.1.2/jzlib-1.1.2.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/github/jnr/jffi/1.2.7/jffi-1.2.7-native.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/jruby/yecht/1.0/yecht-1.0.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/jruby/jcodings/jcodings/1.0.10/jcodings-1.0.10.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/github/jnr/jnr-netdb/1.1.2/jnr-netdb-1.1.2.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/github/jnr/jnr-unixsocket/0.3/jnr-unixsocket-0.3.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/martiansoftware/nailgun-server/0.9.1/nailgun-server-0.9.1.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/github/jnr/jnr-enxio/0.4/jnr-enxio-0.4.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/github/jnr/jnr-ffi/1.0.7/jnr-ffi-1.0.7.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/ow2/asm/asm/4.0/asm-4.0.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/yaml/snakeyaml/1.13/snakeyaml-1.13.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/jruby/extras/bytelist/1.0.11/bytelist-1.0.11.jar')
JBUNDLER_JRUBY_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/github/jnr/jnr-x86asm/1.0.2/jnr-x86asm-1.0.2.jar')
JBUNDLER_JRUBY_CLASSPATH.freeze
JBUNDLER_TEST_CLASSPATH = []
JBUNDLER_TEST_CLASSPATH.freeze
JBUNDLER_CLASSPATH = []
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/tomcat/tomcat-jdbc/7.0.50/tomcat-jdbc-7.0.50.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/jdbi/jdbi/2.55/jdbi-2.55.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/eclipse/jetty/jetty-continuation/8.1.2.v20120308/jetty-continuation-8.1.2.v20120308.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/fasterxml/jackson/core/jackson-annotations/2.4.0/jackson-annotations-2.4.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/google/guava/guava/17.0/guava-17.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/ibm/db2/jcc/db2jcc_license_cu/9.7/db2jcc_license_cu-9.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/eclipse/jetty/jetty-client/8.1.2.v20120308/jetty-client-8.1.2.v20120308.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/commons/commons-lang3/3.0/commons-lang3-3.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/eclipse/jetty/jetty-util/8.1.2.v20120308/jetty-util-8.1.2.v20120308.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/unboundid/unboundid-ldapsdk/2.3.6/unboundid-ldapsdk-2.3.6.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/io/dropwizard/metrics/metrics-httpclient/3.1.0/metrics-httpclient-3.1.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-codec/commons-codec/1.6/commons-codec-1.6.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/fasterxml/jackson/core/jackson-databind/2.4.2/jackson-databind-2.4.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/ibm/db2/jcc/db2jcc4/9.7/db2jcc4-9.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/codehaus/jackson/jackson-mapper-lgpl/1.9.9/jackson-mapper-lgpl-1.9.9.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/google/code/findbugs/annotations/2.0.3/annotations-2.0.3.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/bouncycastle/bcpkix-jdk15on/1.49/bcpkix-jdk15on-1.49.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/io/dropwizard/metrics/metrics-json/3.1.0/metrics-json-3.1.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/eclipse/jetty/jetty-http/8.1.2.v20120308/jetty-http-8.1.2.v20120308.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/eclipse/jetty/jetty-io/8.1.2.v20120308/jetty-io-8.1.2.v20120308.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/eclipse/jetty/jetty-servlets/8.1.2.v20120308/jetty-servlets-8.1.2.v20120308.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/bouncycastle/bcprov-jdk15on/1.49/bcprov-jdk15on-1.49.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/io/dropwizard/metrics/metrics-core/3.1.0/metrics-core-3.1.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/io/dropwizard/metrics/metrics-jvm/3.1.0/metrics-jvm-3.1.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/fasterxml/jackson/core/jackson-core/2.4.2/jackson-core-2.4.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/codehaus/jackson/jackson-core-lgpl/1.9.9/jackson-core-lgpl-1.9.9.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/tomcat/tomcat-juli/7.0.50/tomcat-juli-7.0.50.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/premierinc/accesskontrol/1.8.0/accesskontrol-1.8.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/httpcomponents/httpclient/4.3.5/httpclient-4.3.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar')
JBUNDLER_CLASSPATH.freeze
